#!/bin/sh
#
# Start TFT Dash display application
#

TFTDASH_DIR="/home/pi/tftdash"

case "$1" in
	start)
		printf "Starting TFT Dash: "
		cd "$TFTDASH_DIR"
		./testsdl 2>&1 &
		echo "OK"
		;;
	stop)
		printf "Stopping TFT Dash: "
		killall testsdl 2>/dev/null
		echo "OK"
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
